services:              
  app:                   
    build: .             
    ports:
      - "8000:8000"    
    volumes:
      - ./database.db:/app/database.db  
    environment:         
      - SECRET_KEY=09d25e094faa6ca2557c818196b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7

